use_frameworks!

platform :ios, '9.0'

target 'DinaYestemirCustomFramework_Example' do
  pod 'DinaYestemirCustomFramework', :path => '../'

  target 'DinaYestemirCustomFramework_Tests' do
    inherit! :search_paths

    
  end
end
